default: &default
 adapter: postgresql
 encoding: unicode
 username: postgres
 password: postgres
 host: localhost
 port: 5432

development:
 <<: *default
 database: home_work_development


test:
 <<: *default
 database: home_work_test

#
production:
 <<: *default
 database: production_home_work